### ISSUE TITLE
Witcher 3 is still crashed on the latest version of dvrpatches. Tested on Atmosphere 1.2.6 on 13.2.1

### ISSUE THREAD

**Issue by zf021600** [exelix11/dvr-patches#20] opened 2022-02-24 17:25 UTC
Witcher 3 is still crashed on the latest version of dvrpatches.
Tested on Atmosphere 1.2.6 on 13.2.1

**Comment by Nooderuni** [comment] 2022-02-25 12:37
Would also like to chime in and say that if there's any kind soul who's willing to invest precious time in providing a workaround on a few of these currently unsupported games(Resident Evil Revelations 1/2 also having similar memory issues) would just be blessed with a million kisses from a panel of singing angels. Now I'm just a casual user, but this patch truly has been one of the best and most practical addition to the Switch ecosystem thus far.

**Comment by exelix11** [comment] 2022-02-25 12:45
This issue is a duplicate of  #4.
It didn't work back then and as nobody made a game patch, of course, it still doesn't work.
I won't maintain game patches for games i'm not interested in, the issue is open to anyone who wants to discuss or provide a patch.

@Nooderuni Please open a new issue about resident evil, specify title ids and versions of the two games. Same as the witcher i can't guarantee i'll provide a patch.

**Closed by exelix11** 2022-02-25 12:45 UTC
