### ISSUE TITLE
Witcher 3 Crash When booting

### ISSUE THREAD

**Issue by wholeshome** [exelix11/dvr-patches#11] opened 2021-11-08 14:46 UTC
After Updating to new sysdvr on firmware 13.1,i open the witcher 3 and its still witcher 3 crashes when opening, can you help fix it?

Name : The witcher 3 wild hunt - complete edition
Title ID = 0100BFE00E9CA000
Update = v3.7 (0100BFE00E9CA800)

and this is  for crash report maybe that can help you 
[01636382504_0100bfe00e9ca000.log](https://github.com/exelix11/dvr-patches/files/7497815/01636382504_0100bfe00e9ca000.log)

**Comment by exelix11** [comment] 2021-11-08 14:48
Witcher 3 is one of the few games that break with these patches and there's no fix available currently.
Duplicate of #4

**Closed** 2021-11-08 14:48 UTC
